// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/signer/v1/signer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerificationStatus is the conclusion of a signature verification. It
// encodes the three signals a verifier can read from a signed statement:
// whether it is signed, whether the cryptographic signature could be
// checked, and whether it verified against the content. A status other
// than VERIFIED is a conclusion, not an execution error.
type VerificationStatus int32

const (
	// UNSPECIFIED means the producer did not record a status. Consumers
	// should fall back to the verified boolean.
	VerificationStatus_UNSPECIFIED VerificationStatus = 0
	// UNSIGNED means the statement carries no signatures.
	VerificationStatus_UNSIGNED VerificationStatus = 1
	// UNVERIFIABLE means the statement is signed but the verifier had no
	// key or trust material to check the signatures against.
	VerificationStatus_UNVERIFIABLE VerificationStatus = 2
	// FAILED means the statement is signed, the verifier checked the
	// signatures against its key or trust material, and none verified.
	VerificationStatus_FAILED VerificationStatus = 3
	// VERIFIED means at least one signature verified against the content.
	// The identities list names the signers that verified.
	VerificationStatus_VERIFIED VerificationStatus = 4
)

// Enum value maps for VerificationStatus.
var (
	VerificationStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNSIGNED",
		2: "UNVERIFIABLE",
		3: "FAILED",
		4: "VERIFIED",
	}
	VerificationStatus_value = map[string]int32{
		"UNSPECIFIED":  0,
		"UNSIGNED":     1,
		"UNVERIFIABLE": 2,
		"FAILED":       3,
		"VERIFIED":     4,
	}
)

func (x VerificationStatus) Enum() *VerificationStatus {
	p := new(VerificationStatus)
	*p = x
	return p
}

func (x VerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_carabiner_signer_v1_signer_proto_enumTypes[0].Descriptor()
}

func (VerificationStatus) Type() protoreflect.EnumType {
	return &file_carabiner_signer_v1_signer_proto_enumTypes[0]
}

func (x VerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationStatus.Descriptor instead.
func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_signer_proto_rawDescGZIP(), []int{0}
}

// Results of the signature verification process
type Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     *SignatureVerification `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_carabiner_signer_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verification.ProtoReflect.Descriptor instead.
func (*Verification) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_signer_proto_rawDescGZIP(), []int{0}
}

func (x *Verification) GetSignature() *SignatureVerification {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SignatureVerification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date when the verification was performed
	Date *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// SignatureVerified is set to true when a hash's signature was verified
	// with at least one key or cert. Verified does not imply any identity check.
	Verified bool `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	// Identities has a list of the identities (sigstore signers or keys)
	// that signed the object.
	Identities []*Identity `protobuf:"bytes,3,rep,name=Identities,proto3" json:"Identities,omitempty"`
	// Message is an optional message that can be populated when a verification
	// was performed successfully.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Error is a message explaining why verification failed.
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Status is the conclusion of the verification. When set, verified is
	// equivalent to status == VERIFIED.
	Status        VerificationStatus `protobuf:"varint,6,opt,name=status,proto3,enum=carabiner.signer.v1.VerificationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureVerification) Reset() {
	*x = SignatureVerification{}
	mi := &file_carabiner_signer_v1_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureVerification) ProtoMessage() {}

func (x *SignatureVerification) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureVerification.ProtoReflect.Descriptor instead.
func (*SignatureVerification) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_signer_proto_rawDescGZIP(), []int{1}
}

func (x *SignatureVerification) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *SignatureVerification) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *SignatureVerification) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *SignatureVerification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignatureVerification) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SignatureVerification) GetStatus() VerificationStatus {
	if x != nil {
		return x.Status
	}
	return VerificationStatus_UNSPECIFIED
}

var File_carabiner_signer_v1_signer_proto protoreflect.FileDescriptor

const file_carabiner_signer_v1_signer_proto_rawDesc = "" +
	"\n" +
	" carabiner/signer/v1/signer.proto\x12\x13carabiner.signer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"carabiner/signer/v1/identity.proto\"X\n" +
	"\fVerification\x12H\n" +
	"\tsignature\x18\x01 \x01(\v2*.carabiner.signer.v1.SignatureVerificationR\tsignature\"\x93\x02\n" +
	"\x15SignatureVerification\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12=\n" +
	"\n" +
	"Identities\x18\x03 \x03(\v2\x1d.carabiner.signer.v1.IdentityR\n" +
	"Identities\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12?\n" +
	"\x06status\x18\x06 \x01(\x0e2'.carabiner.signer.v1.VerificationStatusR\x06status*_\n" +
	"\x12VerificationStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bUNSIGNED\x10\x01\x12\x10\n" +
	"\fUNVERIFIABLE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\f\n" +
	"\bVERIFIED\x10\x04B\xbc\x01\n" +
	"\x17com.carabiner.signer.v1B\vSignerProtoP\x01Z&github.com/carabiner-dev/signer/api/v1\xa2\x02\x03CSX\xaa\x02\x13Carabiner.Signer.V1\xca\x02\x13Carabiner\\Signer\\V1\xe2\x02\x1fCarabiner\\Signer\\V1\\GPBMetadata\xea\x02\x15Carabiner::Signer::V1b\x06proto3"

var (
	file_carabiner_signer_v1_signer_proto_rawDescOnce sync.Once
	file_carabiner_signer_v1_signer_proto_rawDescData []byte
)

func file_carabiner_signer_v1_signer_proto_rawDescGZIP() []byte {
	file_carabiner_signer_v1_signer_proto_rawDescOnce.Do(func() {
		file_carabiner_signer_v1_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_signer_proto_rawDesc), len(file_carabiner_signer_v1_signer_proto_rawDesc)))
	})
	return file_carabiner_signer_v1_signer_proto_rawDescData
}

var file_carabiner_signer_v1_signer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carabiner_signer_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_carabiner_signer_v1_signer_proto_goTypes = []any{
	(VerificationStatus)(0),       // 0: carabiner.signer.v1.VerificationStatus
	(*Verification)(nil),          // 1: carabiner.signer.v1.Verification
	(*SignatureVerification)(nil), // 2: carabiner.signer.v1.SignatureVerification
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Identity)(nil),              // 4: carabiner.signer.v1.Identity
}
var file_carabiner_signer_v1_signer_proto_depIdxs = []int32{
	2, // 0: carabiner.signer.v1.Verification.signature:type_name -> carabiner.signer.v1.SignatureVerification
	3, // 1: carabiner.signer.v1.SignatureVerification.date:type_name -> google.protobuf.Timestamp
	4, // 2: carabiner.signer.v1.SignatureVerification.Identities:type_name -> carabiner.signer.v1.Identity
	0, // 3: carabiner.signer.v1.SignatureVerification.status:type_name -> carabiner.signer.v1.VerificationStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_carabiner_signer_v1_signer_proto_init() }
func file_carabiner_signer_v1_signer_proto_init() {
	if File_carabiner_signer_v1_signer_proto != nil {
		return
	}
	file_carabiner_signer_v1_identity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_signer_proto_rawDesc), len(file_carabiner_signer_v1_signer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_signer_v1_signer_proto_goTypes,
		DependencyIndexes: file_carabiner_signer_v1_signer_proto_depIdxs,
		EnumInfos:         file_carabiner_signer_v1_signer_proto_enumTypes,
		MessageInfos:      file_carabiner_signer_v1_signer_proto_msgTypes,
	}.Build()
	File_carabiner_signer_v1_signer_proto = out.File
	file_carabiner_signer_v1_signer_proto_goTypes = nil
	file_carabiner_signer_v1_signer_proto_depIdxs = nil
}
