// Code generated by counterfeiter. DO NOT EDIT.
package bundlefakes

import (
	"context"
	"sync"

	"github.com/carabiner-dev/signer/bundle"
	"github.com/sigstore/sigstore-go/pkg/sign"
)

type FakeIdentity struct {
	CertificateProviderStub        func() (sign.CertificateProvider, *sign.CertificateProviderOptions)
	certificateProviderMutex       sync.RWMutex
	certificateProviderArgsForCall []struct {
	}
	certificateProviderReturns struct {
		result1 sign.CertificateProvider
		result2 *sign.CertificateProviderOptions
	}
	certificateProviderReturnsOnCall map[int]struct {
		result1 sign.CertificateProvider
		result2 *sign.CertificateProviderOptions
	}
	KeypairStub        func() sign.Keypair
	keypairMutex       sync.RWMutex
	keypairArgsForCall []struct {
	}
	keypairReturns struct {
		result1 sign.Keypair
	}
	keypairReturnsOnCall map[int]struct {
		result1 sign.Keypair
	}
	PrepareStub        func(context.Context) error
	prepareMutex       sync.RWMutex
	prepareArgsForCall []struct {
		arg1 context.Context
	}
	prepareReturns struct {
		result1 error
	}
	prepareReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIdentity) CertificateProvider() (sign.CertificateProvider, *sign.CertificateProviderOptions) {
	fake.certificateProviderMutex.Lock()
	ret, specificReturn := fake.certificateProviderReturnsOnCall[len(fake.certificateProviderArgsForCall)]
	fake.certificateProviderArgsForCall = append(fake.certificateProviderArgsForCall, struct {
	}{})
	stub := fake.CertificateProviderStub
	fakeReturns := fake.certificateProviderReturns
	fake.recordInvocation("CertificateProvider", []interface{}{})
	fake.certificateProviderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIdentity) CertificateProviderCallCount() int {
	fake.certificateProviderMutex.RLock()
	defer fake.certificateProviderMutex.RUnlock()
	return len(fake.certificateProviderArgsForCall)
}

func (fake *FakeIdentity) CertificateProviderCalls(stub func() (sign.CertificateProvider, *sign.CertificateProviderOptions)) {
	fake.certificateProviderMutex.Lock()
	defer fake.certificateProviderMutex.Unlock()
	fake.CertificateProviderStub = stub
}

func (fake *FakeIdentity) CertificateProviderReturns(result1 sign.CertificateProvider, result2 *sign.CertificateProviderOptions) {
	fake.certificateProviderMutex.Lock()
	defer fake.certificateProviderMutex.Unlock()
	fake.CertificateProviderStub = nil
	fake.certificateProviderReturns = struct {
		result1 sign.CertificateProvider
		result2 *sign.CertificateProviderOptions
	}{result1, result2}
}

func (fake *FakeIdentity) CertificateProviderReturnsOnCall(i int, result1 sign.CertificateProvider, result2 *sign.CertificateProviderOptions) {
	fake.certificateProviderMutex.Lock()
	defer fake.certificateProviderMutex.Unlock()
	fake.CertificateProviderStub = nil
	if fake.certificateProviderReturnsOnCall == nil {
		fake.certificateProviderReturnsOnCall = make(map[int]struct {
			result1 sign.CertificateProvider
			result2 *sign.CertificateProviderOptions
		})
	}
	fake.certificateProviderReturnsOnCall[i] = struct {
		result1 sign.CertificateProvider
		result2 *sign.CertificateProviderOptions
	}{result1, result2}
}

func (fake *FakeIdentity) Keypair() sign.Keypair {
	fake.keypairMutex.Lock()
	ret, specificReturn := fake.keypairReturnsOnCall[len(fake.keypairArgsForCall)]
	fake.keypairArgsForCall = append(fake.keypairArgsForCall, struct {
	}{})
	stub := fake.KeypairStub
	fakeReturns := fake.keypairReturns
	fake.recordInvocation("Keypair", []interface{}{})
	fake.keypairMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIdentity) KeypairCallCount() int {
	fake.keypairMutex.RLock()
	defer fake.keypairMutex.RUnlock()
	return len(fake.keypairArgsForCall)
}

func (fake *FakeIdentity) KeypairCalls(stub func() sign.Keypair) {
	fake.keypairMutex.Lock()
	defer fake.keypairMutex.Unlock()
	fake.KeypairStub = stub
}

func (fake *FakeIdentity) KeypairReturns(result1 sign.Keypair) {
	fake.keypairMutex.Lock()
	defer fake.keypairMutex.Unlock()
	fake.KeypairStub = nil
	fake.keypairReturns = struct {
		result1 sign.Keypair
	}{result1}
}

func (fake *FakeIdentity) KeypairReturnsOnCall(i int, result1 sign.Keypair) {
	fake.keypairMutex.Lock()
	defer fake.keypairMutex.Unlock()
	fake.KeypairStub = nil
	if fake.keypairReturnsOnCall == nil {
		fake.keypairReturnsOnCall = make(map[int]struct {
			result1 sign.Keypair
		})
	}
	fake.keypairReturnsOnCall[i] = struct {
		result1 sign.Keypair
	}{result1}
}

func (fake *FakeIdentity) Prepare(arg1 context.Context) error {
	fake.prepareMutex.Lock()
	ret, specificReturn := fake.prepareReturnsOnCall[len(fake.prepareArgsForCall)]
	fake.prepareArgsForCall = append(fake.prepareArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PrepareStub
	fakeReturns := fake.prepareReturns
	fake.recordInvocation("Prepare", []interface{}{arg1})
	fake.prepareMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIdentity) PrepareCallCount() int {
	fake.prepareMutex.RLock()
	defer fake.prepareMutex.RUnlock()
	return len(fake.prepareArgsForCall)
}

func (fake *FakeIdentity) PrepareCalls(stub func(context.Context) error) {
	fake.prepareMutex.Lock()
	defer fake.prepareMutex.Unlock()
	fake.PrepareStub = stub
}

func (fake *FakeIdentity) PrepareArgsForCall(i int) context.Context {
	fake.prepareMutex.RLock()
	defer fake.prepareMutex.RUnlock()
	argsForCall := fake.prepareArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIdentity) PrepareReturns(result1 error) {
	fake.prepareMutex.Lock()
	defer fake.prepareMutex.Unlock()
	fake.PrepareStub = nil
	fake.prepareReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIdentity) PrepareReturnsOnCall(i int, result1 error) {
	fake.prepareMutex.Lock()
	defer fake.prepareMutex.Unlock()
	fake.PrepareStub = nil
	if fake.prepareReturnsOnCall == nil {
		fake.prepareReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.prepareReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIdentity) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIdentity) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bundle.Identity = new(FakeIdentity)
