// Code generated by counterfeiter. DO NOT EDIT.
package signerfakes

import (
	"sync"

	"github.com/carabiner-dev/signer"
	"github.com/carabiner-dev/signer/options"
)

type FakeBackend struct {
	NameStub        func() options.Backend
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 options.Backend
	}
	nameReturnsOnCall map[int]struct {
		result1 options.Backend
	}
	SignMessageStub        func([]byte, ...options.SignOptFn) (signer.SignedArtifact, error)
	signMessageMutex       sync.RWMutex
	signMessageArgsForCall []struct {
		arg1 []byte
		arg2 []options.SignOptFn
	}
	signMessageReturns struct {
		result1 signer.SignedArtifact
		result2 error
	}
	signMessageReturnsOnCall map[int]struct {
		result1 signer.SignedArtifact
		result2 error
	}
	SignStatementStub        func([]byte, ...options.SignOptFn) (signer.SignedArtifact, error)
	signStatementMutex       sync.RWMutex
	signStatementArgsForCall []struct {
		arg1 []byte
		arg2 []options.SignOptFn
	}
	signStatementReturns struct {
		result1 signer.SignedArtifact
		result2 error
	}
	signStatementReturnsOnCall map[int]struct {
		result1 signer.SignedArtifact
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackend) Name() options.Backend {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBackend) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeBackend) NameCalls(stub func() options.Backend) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeBackend) NameReturns(result1 options.Backend) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 options.Backend
	}{result1}
}

func (fake *FakeBackend) NameReturnsOnCall(i int, result1 options.Backend) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 options.Backend
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 options.Backend
	}{result1}
}

func (fake *FakeBackend) SignMessage(arg1 []byte, arg2 ...options.SignOptFn) (signer.SignedArtifact, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.signMessageMutex.Lock()
	ret, specificReturn := fake.signMessageReturnsOnCall[len(fake.signMessageArgsForCall)]
	fake.signMessageArgsForCall = append(fake.signMessageArgsForCall, struct {
		arg1 []byte
		arg2 []options.SignOptFn
	}{arg1Copy, arg2})
	stub := fake.SignMessageStub
	fakeReturns := fake.signMessageReturns
	fake.recordInvocation("SignMessage", []interface{}{arg1Copy, arg2})
	fake.signMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackend) SignMessageCallCount() int {
	fake.signMessageMutex.RLock()
	defer fake.signMessageMutex.RUnlock()
	return len(fake.signMessageArgsForCall)
}

func (fake *FakeBackend) SignMessageCalls(stub func([]byte, ...options.SignOptFn) (signer.SignedArtifact, error)) {
	fake.signMessageMutex.Lock()
	defer fake.signMessageMutex.Unlock()
	fake.SignMessageStub = stub
}

func (fake *FakeBackend) SignMessageArgsForCall(i int) ([]byte, []options.SignOptFn) {
	fake.signMessageMutex.RLock()
	defer fake.signMessageMutex.RUnlock()
	argsForCall := fake.signMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBackend) SignMessageReturns(result1 signer.SignedArtifact, result2 error) {
	fake.signMessageMutex.Lock()
	defer fake.signMessageMutex.Unlock()
	fake.SignMessageStub = nil
	fake.signMessageReturns = struct {
		result1 signer.SignedArtifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) SignMessageReturnsOnCall(i int, result1 signer.SignedArtifact, result2 error) {
	fake.signMessageMutex.Lock()
	defer fake.signMessageMutex.Unlock()
	fake.SignMessageStub = nil
	if fake.signMessageReturnsOnCall == nil {
		fake.signMessageReturnsOnCall = make(map[int]struct {
			result1 signer.SignedArtifact
			result2 error
		})
	}
	fake.signMessageReturnsOnCall[i] = struct {
		result1 signer.SignedArtifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) SignStatement(arg1 []byte, arg2 ...options.SignOptFn) (signer.SignedArtifact, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.signStatementMutex.Lock()
	ret, specificReturn := fake.signStatementReturnsOnCall[len(fake.signStatementArgsForCall)]
	fake.signStatementArgsForCall = append(fake.signStatementArgsForCall, struct {
		arg1 []byte
		arg2 []options.SignOptFn
	}{arg1Copy, arg2})
	stub := fake.SignStatementStub
	fakeReturns := fake.signStatementReturns
	fake.recordInvocation("SignStatement", []interface{}{arg1Copy, arg2})
	fake.signStatementMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackend) SignStatementCallCount() int {
	fake.signStatementMutex.RLock()
	defer fake.signStatementMutex.RUnlock()
	return len(fake.signStatementArgsForCall)
}

func (fake *FakeBackend) SignStatementCalls(stub func([]byte, ...options.SignOptFn) (signer.SignedArtifact, error)) {
	fake.signStatementMutex.Lock()
	defer fake.signStatementMutex.Unlock()
	fake.SignStatementStub = stub
}

func (fake *FakeBackend) SignStatementArgsForCall(i int) ([]byte, []options.SignOptFn) {
	fake.signStatementMutex.RLock()
	defer fake.signStatementMutex.RUnlock()
	argsForCall := fake.signStatementArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBackend) SignStatementReturns(result1 signer.SignedArtifact, result2 error) {
	fake.signStatementMutex.Lock()
	defer fake.signStatementMutex.Unlock()
	fake.SignStatementStub = nil
	fake.signStatementReturns = struct {
		result1 signer.SignedArtifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) SignStatementReturnsOnCall(i int, result1 signer.SignedArtifact, result2 error) {
	fake.signStatementMutex.Lock()
	defer fake.signStatementMutex.Unlock()
	fake.SignStatementStub = nil
	if fake.signStatementReturnsOnCall == nil {
		fake.signStatementReturnsOnCall = make(map[int]struct {
			result1 signer.SignedArtifact
			result2 error
		})
	}
	fake.signStatementReturnsOnCall[i] = struct {
		result1 signer.SignedArtifact
		result2 error
	}{result1, result2}
}

func (fake *FakeBackend) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackend) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ signer.Backend = new(FakeBackend)
