// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: carabiner/signer/v1/identity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity captures a signer identity. An identity can one of:
//
//	a) A sigstore identity
//	b) A key
//	c) A reference to an identity defined outside the policy
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sigstore      *IdentitySigstore      `protobuf:"bytes,2,opt,name=sigstore,proto3,oneof" json:"sigstore,omitempty"`
	Key           *IdentityKey           `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Ref           *IdentityRef           `protobuf:"bytes,4,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetSigstore() *IdentitySigstore {
	if x != nil {
		return x.Sigstore
	}
	return nil
}

func (x *Identity) GetKey() *IdentityKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Identity) GetRef() *IdentityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

// IdentitySigstore represents the identity data in a Fulcio cert.
type IdentitySigstore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          *string                `protobuf:"bytes,1,opt,name=mode,proto3,oneof" json:"mode,omitempty"`   // exact | regexp
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`     // https://accounts.google.com
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"` //  "identity": "puerco@gmail.com"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySigstore) Reset() {
	*x = IdentitySigstore{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySigstore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySigstore) ProtoMessage() {}

func (x *IdentitySigstore) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySigstore.ProtoReflect.Descriptor instead.
func (*IdentitySigstore) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentitySigstore) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *IdentitySigstore) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentitySigstore) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

// IdentityKey registers the data of a key used to sign attestations.
type IdentityKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Key ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Identity type
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Public key data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityKey) Reset() {
	*x = IdentityKey{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKey) ProtoMessage() {}

func (x *IdentityKey) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKey.ProtoReflect.Descriptor instead.
func (*IdentityKey) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentityKey) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// IdentityRef represents an identity defined outside of the policy. Most commonly
// these identities will be defined at the policy set level to have a common
// definition that can be reused by all policies in a set.
type IdentityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRef) Reset() {
	*x = IdentityRef{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRef) ProtoMessage() {}

func (x *IdentityRef) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRef.ProtoReflect.Descriptor instead.
func (*IdentityRef) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_carabiner_signer_v1_identity_proto protoreflect.FileDescriptor

const file_carabiner_signer_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\"carabiner/signer/v1/identity.proto\x12\x13carabiner.signer.v1\"\xf1\x01\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\bsigstore\x18\x02 \x01(\v2%.carabiner.signer.v1.IdentitySigstoreH\x00R\bsigstore\x88\x01\x01\x127\n" +
	"\x03key\x18\x03 \x01(\v2 .carabiner.signer.v1.IdentityKeyH\x01R\x03key\x88\x01\x01\x127\n" +
	"\x03ref\x18\x04 \x01(\v2 .carabiner.signer.v1.IdentityRefH\x02R\x03ref\x88\x01\x01B\v\n" +
	"\t_sigstoreB\x06\n" +
	"\x04_keyB\x06\n" +
	"\x04_ref\"h\n" +
	"\x10IdentitySigstore\x12\x17\n" +
	"\x04mode\x18\x01 \x01(\tH\x00R\x04mode\x88\x01\x01\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentityB\a\n" +
	"\x05_mode\"E\n" +
	"\vIdentityKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"\x1d\n" +
	"\vIdentityRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\xbe\x01\n" +
	"\x17com.carabiner.signer.v1B\rIdentityProtoP\x01Z&github.com/carabiner-dev/policy/api/v1\xa2\x02\x03CSX\xaa\x02\x13Carabiner.Signer.V1\xca\x02\x13Carabiner\\Signer\\V1\xe2\x02\x1fCarabiner\\Signer\\V1\\GPBMetadata\xea\x02\x15Carabiner::Signer::V1b\x06proto3"

var (
	file_carabiner_signer_v1_identity_proto_rawDescOnce sync.Once
	file_carabiner_signer_v1_identity_proto_rawDescData []byte
)

func file_carabiner_signer_v1_identity_proto_rawDescGZIP() []byte {
	file_carabiner_signer_v1_identity_proto_rawDescOnce.Do(func() {
		file_carabiner_signer_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_identity_proto_rawDesc), len(file_carabiner_signer_v1_identity_proto_rawDesc)))
	})
	return file_carabiner_signer_v1_identity_proto_rawDescData
}

var file_carabiner_signer_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_carabiner_signer_v1_identity_proto_goTypes = []any{
	(*Identity)(nil),         // 0: carabiner.signer.v1.Identity
	(*IdentitySigstore)(nil), // 1: carabiner.signer.v1.IdentitySigstore
	(*IdentityKey)(nil),      // 2: carabiner.signer.v1.IdentityKey
	(*IdentityRef)(nil),      // 3: carabiner.signer.v1.IdentityRef
}
var file_carabiner_signer_v1_identity_proto_depIdxs = []int32{
	1, // 0: carabiner.signer.v1.Identity.sigstore:type_name -> carabiner.signer.v1.IdentitySigstore
	2, // 1: carabiner.signer.v1.Identity.key:type_name -> carabiner.signer.v1.IdentityKey
	3, // 2: carabiner.signer.v1.Identity.ref:type_name -> carabiner.signer.v1.IdentityRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_carabiner_signer_v1_identity_proto_init() }
func file_carabiner_signer_v1_identity_proto_init() {
	if File_carabiner_signer_v1_identity_proto != nil {
		return
	}
	file_carabiner_signer_v1_identity_proto_msgTypes[0].OneofWrappers = []any{}
	file_carabiner_signer_v1_identity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_identity_proto_rawDesc), len(file_carabiner_signer_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_signer_v1_identity_proto_goTypes,
		DependencyIndexes: file_carabiner_signer_v1_identity_proto_depIdxs,
		MessageInfos:      file_carabiner_signer_v1_identity_proto_msgTypes,
	}.Build()
	File_carabiner_signer_v1_identity_proto = out.File
	file_carabiner_signer_v1_identity_proto_goTypes = nil
	file_carabiner_signer_v1_identity_proto_depIdxs = nil
}
