# SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: verify-roots-sync

on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {}

permissions: {}

jobs:
  verify-roots-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Verify signing configs are in sync with upstream
      run: bash hack/roots-verify.sh
